[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "NanoNN"
dynamic = ["version"]
dependencies = ["numpy >= 1.26",]

[tool.setuptools]
packages = ["nano_nn",]
